# Dockerfile to build Ubuntu22.04x64 + OpenFOAM-9 + Python 3.10

FROM ubuntu:22.04

# Use bash as shell
SHELL ["/bin/bash", "-c"]

# Update and install dependencies, parallel and utilities
RUN apt-get update && apt-get dist-upgrade -y                                &&\
apt-get install -y libglib2.0-dev libboost-all-dev valgrind cmake gfortran     \
libhypre-dev libhdf5-openmpi-dev openmpi-bin  mpi check python3 python3-pip zip\
 libopenmpi-dev libtrilinos-zoltan-dev mpich gcc autoconf automake libtool git \
make libltdl-dev pkg-config libyaml-dev sudo neovim                            \
python3-setuptools                                                           &&\
apt-get clean && apt-get autoremove --purge                                  &&\
rm -rf /var/lib/apt/lists/*                                                  &&\
adduser --shell /bin/bash --disabled-password --gecos '' hig_user            &&\
passwd -d hig_user                                                           &&\
addgroup hig_user sudo

# Using user hig_user and its home dir
USER      hig_user
WORKDIR   /home/hig_user/HigFlow
ENV       USER         "hig_user"
ENV       HOME         "/home/hig_user/"


COPY --chown=hig_user:hig_user . "$HOME/HigFlow/"

# RUN pip3 install wheel sphinx sphinx_rtd_theme sphinx-markdown-builder
RUN pip3 install ruamel.yaml
RUN cd $HOME/HigFlow/bibliotecas/                                            &&\
tar -vzxf petsc-3.14.0.tar.gz                                                &&\
cd petsc-3.14.0/                                                             &&\
 ./configure --prefix=/opt/petsc-3.14.0 --with-shared-libraries=1  --with-mpi-dir=/usr  --download-fblaslapack --with-debubbing=yes --with-yaml=1 --with-hdf5-dir=/usr/lib/x86_64-linux-gnu/hdf5/openmpi/lib --with-hdf5=1 --with-hdf5-fortran-bindings=1 --with-mpi-f90module-visibility=0 --download-hypre=1 &&\
parch=$(tail -200 configure.log | awk '/PETSC_ARCH/ {print $2}')             &&\
pdir=$(tail -200 configure.log | awk '/PETSC_DIR/ {print $2}')               &&\
make PETSC_DIR=$pdir PETSC_ARCH=$parch all                                   &&\
sudo make PETSC_DIR=$pdir PETSC_ARCH=$parch install                          &&\
make PETSC_DIR=$pdir PETSC_ARCH=$parch check                                 &&\
echo "export PETSC_DIR=$pdir" >> $HOME/.varsrc                               &&\
echo "export PETSC_ARCH=$parch" >> $HOME/.varsrc                             &&\
echo "export HIGTREE_DIR=$HOME/HigFlow/higtree" >> $HOME/.varsrc             &&\
echo "export HIGFLOW_DIR=$HOME/HigFlow/higflow" >> $HOME/.varsrc             &&\
echo 'export PETSC_EXTRA_LIB="-lmpi"' >> $HOME/.varsrc                       &&\
echo '. $HOME/.varsrc' >> $HOME/.bashrc                                     &&\
echo "export LD_LIBRARY_PATH=\$PETSC_DIR/\$PETSC_ARCH/lib:\$LD_LIBRARY_PATH">>$HOME/.bashrc &&\
cd $HOME/HigFlow/bibliotecas/                                                &&\
unzip libfyaml-master.zip                                                    &&\
chmod 777 libfyaml-master                                                    &&\
cd libfyaml-master/                                                          &&\
./bootstrap.sh && ./configure && make && sudo make install                   &&\
sudo apt-get update && sudo apt -y install libyaml-dev                       &&\
sudo /sbin/ldconfig -v
