# Dockerfile to build Ubuntu22.04x64 + OpenFOAM-9 + Python 3.10

FROM ubuntu:22.04

# Use bash as shell
SHELL ["/bin/bash", "-c"]

# Update and install dependencies, parallel and utilities
RUN apt-get update && apt-get dist-upgrade -y                                &&\
apt-get install -y libglib2.0-dev libboost-all-dev valgrind cmake gfortran     \
libhypre-dev libhdf5-openmpi-dev openmpi-bin  mpi check python3 python3-pip zip\
 libopenmpi-dev libtrilinos-zoltan-dev mpich gcc autoconf automake libtool git \
make libltdl-dev pkg-config libyaml-dev sudo                                   \
python3-setuptools                                                           &&\
apt-get clean && apt-get autoremove --purge                                  &&\
rm -rf /var/lib/apt/lists/*                                                  &&\
adduser --shell /bin/bash --disabled-password --gecos '' hig_user            &&\
passwd -d hig_user                                                           &&\
addgroup hig_user sudo

# Using user hig_user and its home dir
USER      hig_user
WORKDIR   /home/hig_user/HigFlow
ENV       USER         "hig_user"
ENV       HOME         "/home/hig_user/"


COPY --chown=hig_user:hig_user . "$HOME/HigFlow/"

RUN pip3 install wheel sphinx sphinx_rtd_theme sphinx-markdown-builder
RUN cd $HOME/HigFlow/bibliotecas/                                            &&\
tar -vzxf petsc-3.14.0.tar.gz                                                &&\
cd petsc-3.14.0/                                                             &&\
./configure --PETSC_ARCH=x86_64 --download-openmpi --download-hdf5             \
--download-hypre --download-fblaslapack --with-debubbing=yes  --with-cc=gcc    \
--with-cxx=g++ --with-fc=gfortran                                            &&\
parch=$(tail -200 configure.log | awk '/PETSC_ARCH/ {print $2}')             &&\
pdir=$(tail -200 configure.log | awk '/PETSC_DIR/ {print $2}')               &&\
make PETSC_DIR=$pdir PETSC_ARCH=$parch all                                   &&\
echo "export PETSC_DIR=$pdir"   >> $HOME/.bashrc                             &&\
echo "export PETSC_ARCH=$parch" >> $HOME/.bashrc                             &&\
echo "export LD_LIBRARY_PATH=\$PETSC_DIR/\$PETSC_ARCH/lib:\$LD_LIBRARY_PATH">>$HOME/.bashrc
