#PBS -N PhDi_121_2
#PBS -l select=1:ncpus=2
#PBS -l walltime=336:00:00 
#PBS -q Higflow

module load higtree/deps

cd /lustre/juniormr/Dt_Test/HigFlow
source varsrc

cd /lustre/juniormr/Dt_Test/HigFlow/higtree
make clean
make DIM=2
make DIM=3

cd /lustre/juniormr/Dt_Test/HigFlow/higflow
make clean
make DIM=2

cd /lustre/juniormr/Dt_Test/HigFlow/higflow/Phases_Diferentes_ptsx121_2
make clean
make
make run
