#!/bin/bash
HIGFLOW_ROOT_DIR="$(dirname "$PWD")"
HIGFLOW_DIR=$HIGFLOW_ROOT_DIR/higflow
HIGFLOW_INC=$HIGFLOW_DIR/include
HIGFLOW_LIB=$HIGFLOW_DIR/lib
HIGTREE_DIR=$HIGFLOW_ROOT_DIR/higtree
HIGTREE_INC=$HIGTREE_DIR/include
HIGTREE_LIB=$HIGTREE_DIR/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HIGFLOW_LIB:$HIGTREE_LIB
export INCLUDE=$INCLUDE:$HIGFLOW_INC:$HIGTREE_INC
export HIGFLOW_DIR
export HIGTREE_DIR