#PBS -N eoptt_k20_ref4
#PBS -l select=1:ncpus=40:nodetype=n56
#PBS -l walltime=336:00:00
#PBS -V
#PBS -m abe
#PBS -M hobitteras@usp.br

module load higtree/deps
module load python/3.10.1

cd ~/HigFlow/
export PYTHONPATH=$(pwd)/bibliotecas
export HIGTREE_DIR=$(pwd)/higtree
export HIGFLOW_DIR=$(pwd)/higflow

### your script goes here

cd $HIGTREE_DIR
make clean
make DIM=2
cd $HIGFLOW_DIR
make clean
make DIM=2
cd example2d_ElectroOsmotic
make build_run IN="eovisc De=1.0 eps=0.1 kappa=20.0 channel" MESH=ref4 NP=24 THREAD=1
