#PBS -N shear_drop_eo
#PBS -l select=1:ncpus=40
#PBS -l walltime=336:00:00
#PBS -V
#PBS -m abe
#PBS -M hobitteras@usp.br

module load higtree/deps
module load python/3.10.1

cd ~/HigFlow/
export PYTHONPATH=$(pwd)/bibliotecas
export HIGTREE_DIR=$(pwd)/higtree
export HIGFLOW_DIR=$(pwd)/higflow

### your script goes here

cd $HIGTREE_DIR
make clean
make DIM=2
cd $HIGFLOW_DIR
cd example2d_ElectroOsmotic
cd master_prog
python3 master.py
