
macro(SeparatePathFromLib var)
    string(REPLACE " " ";" var_list ${var})
    set(_LIB_PATH "")
    set(_LIB_NAMES "")
    foreach(v ${var_list})
        if(${v} MATCHES "-L")
            string(REPLACE "-L" "" _v ${v})
            set(_LIB_PATH ${_v})
        elseif(${v} MATCHES "-l")
            string(REPLACE "-l" "" _v ${v})
            list(APPEND _LIB_NAMES ${_v})
        endif()
    endforeach()
    foreach(lib ${_LIB_NAMES})
        find_library(FOUND_LIB_${lib} ${lib} PATHS ${_LIB_PATH}) 
        list(APPEND _LIBS ${FOUND_LIB_${lib}})
    endforeach()
endmacro()
